### PR TITLE
Translated file

### PR DESCRIPTION
**Pull request by THE-COB**
Sorry if this was not supposed to happen

### CODE REVIEW

**Comment by THE-COB** [comment]
I think this was issue number 74

**Comment by labuladong** [comment]
It's OK if you finish issue 74, but it seems that you translate the wrong file?

#74 translates [密码技术.md](https://github.com/labuladong/fucking-algorithm/blob/english/common_knowledge/%E5%AF%86%E7%A0%81%E6%8A%80%E6%9C%AF.md)

But your PR translates [翻译约定（必读）.md](https://github.com/labuladong/fucking-algorithm/blob/english/%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A%EF%BC%88%E5%BF%85%E8%AF%BB%EF%BC%89.md)

**Comment by THE-COB** [comment]
Oh my bad, should I change something or have you got it?

**Comment by labuladong** [comment]
Do not delete the original file [翻译约定（必读）.md](https://github.com/labuladong/fucking-algorithm/blob/english/%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A%EF%BC%88%E5%BF%85%E8%AF%BB%EF%BC%89.md). You can add a new file, maybe "translation_requirements.md" and put your work in that file, then this PR will be merged~

**Comment by THE-COB** [comment]
Alright I'll do that

**Pull request closed without merging**
